services:
  - type: static
    name: kiddo-sdui-homepage
    repo: https://github.com/Shubhamsah27/Kiddo-assignment
    branch: main
    buildCommand: npm install && npm run build
    publishDir: dist
